name: CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: GitHub Action for Heroku
      uses: actions/heroku@1.0.0

